package ENTITY;
// Generated 11-12-2016 14:12:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="dejmobile"
)
public class Cliente  implements java.io.Serializable {


     private String rutCliente;
     private Comuna comuna;
     private int clave;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String direccion;
     private int numeracion;
     private int telefono;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Cliente() {
    }

	
    public Cliente(String rutCliente, Comuna comuna, int clave, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, int numeracion, int telefono) {
        this.rutCliente = rutCliente;
        this.comuna = comuna;
        this.clave = clave;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.direccion = direccion;
        this.numeracion = numeracion;
        this.telefono = telefono;
    }
    public Cliente(String rutCliente, Comuna comuna, int clave, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, int numeracion, int telefono, Set<Solicitud> solicituds) {
       this.rutCliente = rutCliente;
       this.comuna = comuna;
       this.clave = clave;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.direccion = direccion;
       this.numeracion = numeracion;
       this.telefono = telefono;
       this.solicituds = solicituds;
    }
   
     @Id 

    
    @Column(name="rutCliente", unique=true, nullable=false, length=50)
    public String getRutCliente() {
        return this.rutCliente;
    }
    
    public void setRutCliente(String rutCliente) {
        this.rutCliente = rutCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idComuna", nullable=false)
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    
    @Column(name="clave", nullable=false)
    public int getClave() {
        return this.clave;
    }
    
    public void setClave(int clave) {
        this.clave = clave;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidoPaterno", nullable=false, length=50)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    
    @Column(name="apellidoMaterno", nullable=false, length=50)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    
    @Column(name="direccion", nullable=false, length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="numeracion", nullable=false)
    public int getNumeracion() {
        return this.numeracion;
    }
    
    public void setNumeracion(int numeracion) {
        this.numeracion = numeracion;
    }

    
    @Column(name="telefono", nullable=false)
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


