package ENTITY;
// Generated 05-12-2016 18:33:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comuna generated by hbm2java
 */
@Entity
@Table(name="comuna"
    ,catalog="dejmobile"
)
public class Comuna  implements java.io.Serializable {


     private Integer idComuna;
     private String nombreComuna;
     private Set clientes = new HashSet(0);

    public Comuna() {
    }

	
    public Comuna(String nombreComuna) {
        this.nombreComuna = nombreComuna;
    }
    public Comuna(String nombreComuna, Set clientes) {
       this.nombreComuna = nombreComuna;
       this.clientes = clientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idComuna", unique=true, nullable=false)
    public Integer getIdComuna() {
        return this.idComuna;
    }
    
    public void setIdComuna(Integer idComuna) {
        this.idComuna = idComuna;
    }

    
    @Column(name="nombreComuna", nullable=false, length=50)
    public String getNombreComuna() {
        return this.nombreComuna;
    }
    
    public void setNombreComuna(String nombreComuna) {
        this.nombreComuna = nombreComuna;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comuna")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


