package ENTITY;
// Generated 05-12-2016 18:33:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Minuto generated by hbm2java
 */
@Entity
@Table(name="minuto"
    ,catalog="dejmobile"
)
public class Minuto  implements java.io.Serializable {


     private Integer idMinuto;
     private String descripcion;
     private int precio;
     private Set solicituds = new HashSet(0);

    public Minuto() {
    }

	
    public Minuto(String descripcion, int precio) {
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public Minuto(String descripcion, int precio, Set solicituds) {
       this.descripcion = descripcion;
       this.precio = precio;
       this.solicituds = solicituds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMinuto", unique=true, nullable=false)
    public Integer getIdMinuto() {
        return this.idMinuto;
    }
    
    public void setIdMinuto(Integer idMinuto) {
        this.idMinuto = idMinuto;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="precio", nullable=false)
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="minuto")
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


